dataset:
  class: src.data.dataset.Cars3D
  params:
    path: ${env:DATA_PATH}/cars
    observation_shape: ${hyperparameters.input_shape}
    url: http://www.scottreed.info/files/nips2015-analogy-data.tar.gz
  svcca_file: ${env:DATA_PATH}/cars/svcca_medium.npz
