checkpoint:
  _target_: tensorflow.keras.callbacks.ModelCheckpoint
  filepath: checkpoint/epoch_{epoch:02d}_model_loss_{model_loss:.2f}
  save_best_only: false
  monitor: model_loss
  save_weights_only: false