callbacks:
  subdirs:
    - layers_outputs
    - checkpoint
    - tensorboard
    - images
  cls:
    - class: src.models.callbacks.SvccaCallback
      params:
        filepath: layers_outputs/layers_activations.{epoch:02d}.npz
    - class: src.models.callbacks.ImageGeneratorCallback
      params:
        filepath: images/generated_image.{epoch:02d}.png
        nb_samples: 3
        latent_shape: ${hyperparameters.latent_shape}
    - class: tensorflow.keras.callbacks.ModelCheckpoint
      params:
        filepath: checkpoint/{epoch:02d}-{model_loss:.2f}-{elbo:.2f}
        save_best_only: true
        monitor: model_loss
    - class: tensorflow.keras.callbacks.TensorBoard
      params:
        log_dir: tensorboard/
