callbacks:
  subdirs:
    - layers_outputs
    - checkpoint
    - tensorboard
    - images
  cls:
    - class: src.models.callbacks.SvccaCallback
      params:
        filepath: layers_outputs/layers_activations.{data_size}_samples.{epoch:02d}.hdf5
        data_path:  ${dataset.sample_file}
        epoch_steps: 1
    - class: tensorflow.keras.callbacks.ModelCheckpoint
      params:
        filepath: checkpoint/{epoch:02d}-{model_loss:.2f}-{reconstruction_loss:.2f}-{kl_loss:.2f}.hdf5
        save_best_only: true
        monitor: model_loss
        save_weights_only: true
    - class: tensorflow.keras.callbacks.TensorBoard
      params:
        log_dir: tensorboard/
    - class: tensorflow.keras.callbacks.EarlyStopping
      params:
        monitor: model_loss
        patience: 5