_target_: vae_ld.data.dsprites.BlueDSpritesFull
path: ${oc.env:DATA_PATH}/dsprites
observation_shape: [64,64,3]
url: https://github.com/deepmind/dsprites-dataset/raw/master/dsprites_ndarray_co1sh3sc6or40x32y32_64x64.npz
data_size: 1474560
name: blue_dsprites_full
factors_shape: [2,3,6,40,32,32]
n_factors: 6