_target_: vae_ld.data.symsol.SymSol
path: ${oc.env:DATA_PATH}/symsol_reduced
observation_shape: [64,64,1]
# TODO: Update url once the reduced dataset is published on KDR
url: "this_is_a_placeholder"
data_size: 112791
name: symsol
factors_shape: []