_target_: vae_ld.models.encoders.load_pre_trained_classifier
model_path: ${oc.env:XP_PATH}/train/latent_None/classifier/${dataset.name}/None/${seed}/final_model
in_shape: ${dataset.observation_shape}
n_layers: ${n_layers}