_target_: vae_ld.models.encoders.load_external_classifier
n_layers: ${n_layers}
model:
  _target_: tensorflow.keras.applications.efficientnet_v2.EfficientNetV2L
  input_shape: ${dataset.observation_shape}
  include_top: false
  pooling: avg