_target_: vae_ld.models.encoders.load_external_classifier
n_layers: ${n_layers}
model:
  _target_: tensorflow.keras.applications.vgg19.VGG19
  in_shape: ${dataset.observation_shape}
  include_top: false
  pooling: avg