callbacks:
  - class: models.svcca_utils.SvccaCallback
    params:
      filepath: "/home/bonheml/Projects/VAE_learning_dynamics/layers_outputs/layers_activations.{epoch:02d}.npz"
  - class: tensorflow.keras.callbacks.ModelCheckpoint
    params:
      filepath: "/tmp/checkpoint/weights.{epoch:02d}-{model_loss:.2f}-{elbo:.2f}.hdf5"