defaults:
  - _self_
  - dataset: cars
  - sampling: sampler

batch_size: 10000
iter_size: 4
seed: 0
model_name: beta_vae
model_seed: 0
latent_shape: 10
model_path: ${oc.env:XP_PATH}/train/latent_${latent_shape}/${model_name}/${dataset.name}/${param_value}/${model_seed}/checkpoint/*
param_value: 1
param_name: beta
var_threshold: 0.1
mean_error_range: 0.1

hydra:
  run:
    dir: ${oc.env:XP_PATH}/${hydra.job.name}/latent_${latent_shape}/${dataset.name}/${model_name}/param_${param_value}/seed_${model_seed}/
  sweep:
    dir: ${oc.env:XP_PATH}/${hydra.job.name}/latent_${latent_shape}/${dataset.name}/${model_name}/param_${param_value}
    subdir: seed_${model_seed}
  job:
    config:
      override_dirname:
        kv_sep: _
        item_sep: /