dataset_name: symsol
model_name: beta_vae
param_name: beta
param_value: 1
overwrite: false
batch_size: 10000
estimator: "CT"

hydra:
  run:
    dir: ${oc.env:XP_PATH}/${hydra.job.name}/${estimator}/${visualisation_tool_ide.name}/${dataset_name}/${model_name}
  sweep:
    dir: ${oc.env:XP_PATH}/${hydra.job.name}/${estimator}/${visualisation_tool_ide.name}/${dataset_name}/
    subdir: ${model_name}
  job:
    config:
      override_dirname:
        kv_sep: _
        item_sep: /

defaults:
  - _self_
  - visualisation_tool_ide: aggregate