model_name: beta_vae
model_epoch: 1069
model_seed: 0
param_value: 1
random_z: false
model_path: ${oc.env:XP_PATH}/VAE_ld/train/${model_name}/${dataset.name}/${param_value}/${model_seed}/checkpoint/epoch_${model_epoch}_*
fname: ${dataset.name}_${model_name}_param_${param_value}_seed_${model_seed}_epoch_${model_epoch}_random_z_${random_z}.pdf

defaults:
  - _self_
  - visualisation_tool: heatmap
  - dataset: cars3d
  - random_state: np_random

hydra:
  run:
    dir: ${oc.env:XP_PATH}/VAE_ld/${hydra.job.name}/${visualisation_tool.name}/${dataset_name}/${model_name}
  sweep:
    dir: ${oc.env:XP_PATH}/VAE_ld/${hydra.job.name}/${visualisation_tool.name}/${dataset_name}
    subdir: ${model_name}
  job:
    config:
      override_dirname:
        kv_sep: _
        item_sep: /