model_name: beta_vae
model_epoch: 1069
model_seed: 0
param_value: 1
random_z: false
latent_dim: 10
n_samples: 16
seed: 0

model_path: ${oc.env:XP_PATH}/VAE_ld/train/${model_name}/${dataset.name}/${param_value}/${model_seed}/checkpoint/epoch_${model_epoch}_*
fname: epoch_${model_epoch}_random_z_${random_z}.pdf

defaults:
  - _self_
  - dataset: cars

hydra:
  run:
    dir: ${oc.env:XP_PATH}/VAE_ld/${hydra.job.name}/${dataset.name}/${model_name}/latent_${latent_dim}/param_${param_value}/seed_${model_seed}
  sweep:
    dir: ${oc.env:XP_PATH}/VAE_ld/${hydra.job.name}/${dataset.name}/${model_name}/latent_${latent_dim}/param_${param_value}
    subdir: seed_${model_seed}
  job:
    config:
      override_dirname:
        kv_sep: _
        item_sep: /