model_name: beta_vae
model_seed: 0
param_value: 1
random_z: false
latent_dim: 10
batch_size: 16
seed: 0

model_path: ${oc.env:XP_PATH}/train/latent_${latent_dim}/${model_name}/${dataset.name}/${param_value}/${model_seed}/checkpoint/final_model
fname: ${model_name}_${param_value}_seed_${model_seed}_random_z_${random_z}.pdf

defaults:
  - _self_
  - dataset: cars
  - sampling: sampler

hydra:
  run:
    dir: ${oc.env:XP_PATH}/${hydra.job.name}/latent_${latent_dim}/${dataset.name}/${model_name}/param_${param_value}/seed_${model_seed}
  sweep:
    dir: ${oc.env:XP_PATH}/${hydra.job.name}/latent_${latent_dim}/${dataset.name}/${model_name}/param_${param_value}
    subdir: seed_${model_seed}
  job:
    config:
      override_dirname:
        kv_sep: _
        item_sep: /