defaults:
  - dataset: dsprites
  - sampling: sampler
  - optimizer: adam
  - _self_

batch_size: 64
model_name: ivae
param_name: beta
param_value: 1
model_seed: 0
latent_shape: 10
plot_prior_mean: true
plot_prior_variance: true
model_path: ${oc.env:XP_PATH}/train/latent_${latent_shape}/${model_name}/${dataset.name}/${param_value}/${model_seed}/final_model

seed: 0
num_items: 10000
var_idx:
  - 0
fname: histogram_${dataset.name}_${model_name}_${param_name}_${param_value}_seed_${model_seed}_${latent_shape}

hydra:
  run:
    dir: ${oc.env:XP_PATH}/${hydra.job.name}/latent_${latent_shape}/${dataset.name}
  sweep:
    dir: ${oc.env:XP_PATH}/${hydra.job.name}/latent_${latent_shape}
    subdir: ${dataset.name}
  job:
    config:
      override_dirname:
        kv_sep: _
        item_sep: /