defaults:
  - dataset: dsprites
  - sampling: sampler
  - classifier: mixture_model
  - _self_

batch_size: 64
model_name: beta_vae
param_name: beta
param_value: 1
model_seed: 0
latent_shape: 10
n_samples: 5
threshold: 0.2
model_path: ${oc.env:XP_PATH}/train/latent_${latent_shape}/${model_name}/${dataset.name}/${param_value}/${model_seed}/checkpoint/*

seed: 0
num_train: 10000
var_idx:
  - 0
fname: mixed_variables_${dataset.name}_${model_name}_${param_name}_${param_value}_seed_${model_seed}_${latent_shape}

hydra:
  run:
    dir: ${oc.env:XP_PATH}/${hydra.job.name}/latent_${latent_shape}/${dataset.name}
  sweep:
    dir: ${oc.env:XP_PATH}/${hydra.job.name}/latent_${latent_shape}
    subdir: ${dataset.name}
  job:
    config:
      override_dirname:
        kv_sep: _
        item_sep: /