dataset_name: cars3d
m1_name: beta_vae
metric_name: cka
overwrite: false
latent_dim: 10

defaults:
  - _self_
  - visualisation_tool: heatmap

hydra:
  run:
    dir: ${oc.env:XP_PATH}/${hydra.job.name}/latent_${latent_dim}/${visualisation_tool.name}/${dataset_name}/${metric_name}/${m1_name}
  sweep:
    dir: ${oc.env:XP_PATH}/${hydra.job.name}/latent_${latent_dim}/${visualisation_tool.name}/${dataset_name}/${metric_name}
    subdir: ${m1_name}
  job:
    config:
      override_dirname:
        kv_sep: _
        item_sep: /