n_samples: 10000
seed: 0
keep_n: 5
selection_type: even
overwrite: false
latent_dim: 10
force_cpu_inference: false

m1_name: beta_vae
p1_name: beta
p1_value: 1
m1_seed: 0
m1_latent_dim: ${latent_dim}

m2_name: ${m1_name}
p2_name: ${p1_name}
p2_value: ${p1_value}
m2_seed: ${m1_seed}
m2_latent_dim: ${latent_dim}

m1_path: ${oc.env:XP_PATH}/train/latent_${m1_latent_dim}/${m1_name}/${dataset.name}/${p1_value}/${m1_seed}/checkpoint/*
m2_path: ${oc.env:XP_PATH}/train/latent_${m2_latent_dim}/${m2_name}/${dataset.name}/${p2_value}/${m2_seed}/checkpoint/*


defaults:
  - _self_
  - dataset: cars
  - similarity_metric: cka

hydra:
  run:
    dir: ${oc.env:XP_PATH}/${hydra.job.name}/latent_${latent_dim}/${dataset.name}/${similarity_metric.name}/${m1_name}/param_${p1_value}/seed_${m1_seed}/${m2_name}/param_${p2_value}/seed_${m2_seed}
  sweep:
    dir: ${oc.env:XP_PATH}/${hydra.job.name}/latent_${latent_dim}/${dataset.name}/${similarity_metric.name}/${m1_name}/param_${p1_value}/seed_${m1_seed}/${m2_name}/param_${p2_value}
    subdir: seed_${m2_seed}
  job:
    config:
      override_dirname:
        kv_sep: _
        item_sep: /
