batch_size: 64
training_steps: 300000
latent_shape: 10
model_seed: 0
seed: ${model_seed}
param_value: 1
source_dataset: celeba
model_folder: final_model
model_path: ${oc.env:XP_PATH}/train/latent_${latent_shape}/${model.name}/${source_dataset}/${param_value}/${model_seed}/${model_folder}
reset: true
encoder_idx:
  - -2
  - -3
decoder_idx:
  - 0

defaults:
  - _self_
  - model: beta_vae
  - dataset: cars
  - sampling: sampler
  - optimizer: adam
  - callbacks:
    - tensorboard
    - image_generator

hydra:
  run:
    dir: ${oc.env:XP_PATH}/${hydra.job.name}/latent_${latent_shape}/${model.name}/${source_dataset}_to_${dataset.name}/${param_value}/${seed}
  sweep:
    dir: ${oc.env:XP_PATH}/${hydra.job.name}/latent_${latent_shape}/${model.name}/${source_dataset}_to_${dataset.name}/${param_value}
    subdir: ${seed}
  job:
    config:
      override_dirname:
        kv_sep: _
        item_sep: /
