defaults:
  - dataset: dsprites
  - sampling: sampler
  - optimizer: adam
  - _self_

batch_size: 64
source_dataset_name: symsol
model_name: beta_vae
param_name: beta
param_value: 1
model_seed: 0
latent_shape: 10
model_path: ${oc.env:XP_PATH}/train/latent_${latent_shape}/${model_name}/${source_dataset_name}/${param_value}/${model_seed}/final_model

seed: 0
num_items: 10000
var_idx:
  - 0
fname: histogram_source_${source_dataset_name}_target_${dataset.name}_${model_name}_${param_name}_${param_value}_seed_${model_seed}_${latent_shape}

hydra:
  run:
    dir: ${oc.env:XP_PATH}/${hydra.job.name}/latent_${latent_shape}/${source_dataset_name}/${dataset.name}
  sweep:
    dir: ${oc.env:XP_PATH}/${hydra.job.name}/latent_${latent_shape}/${source_dataset_name}/
    subdir: ${dataset.name}
  job:
    config:
      override_dirname:
        kv_sep: _
        item_sep: /