defaults:
  - encoder: convolutional
  - decoder: convolutional
  - reconstruction_loss_fn: bernoulli

_target_: vae_ld.models.vaes.BetaVAE
# Beta tested by Locatello et al.: [1, 2, 4, 6, 8, 10]
beta: 1
save_activations: ${hyperparameters.save_activations}
