model:
  class: src.models.vaes.BetaVAE
  params:
    # Beta tested by Locatello et al.: [1, 2, 4, 6, 8, 10]
    beta: 1
  encoder:
    class: src.models.encoders.ConvolutionalEncoder
  decoder:
    class: src.models.decoders.DeconvolutionalDecoder
