model:
  class: src.models.vaes.AnnealedVAE
  params:
    gamma: 1000
    # Max capacity tested by Locatello et al. : [5, 10, 25, 50, 75, 100]
    max_capacity: 5
    iteration_threshold: 100000
    save_activations: ${hyperparameters.save_activations}
  encoder:
    class: src.models.encoders.ConvolutionalEncoder
    params:
      input_shape: ${hyperparameters.input_shape}
      output_shape: ${hyperparameters.latent_shape}
      save_activations: ${hyperparameters.save_activations}
  decoder:
    class: src.models.decoders.DeconvolutionalDecoder
    params:
      input_shape: ${hyperparameters.latent_shape}
      output_shape: ${hyperparameters.input_shape}
      save_activations: ${hyperparameters.save_activations}
