model:
  class: src.models.vaes.BetaVAE
  params:
    # Beta tested by Locatello et al.: [1, 2, 4, 6, 8, 10]
    beta: 1
    save_activations: ${hyperparameters.save_activations}
  encoder:
    class: src.models.encoders.ConvolutionalEncoder
    params:
      input_shape: ${dataset.params.observation_shape}
      output_shape: ${hyperparameters.latent_shape}
      save_activations: ${hyperparameters.save_activations}
  decoder:
    class: src.models.decoders.DeconvolutionalDecoder
    params:
      input_shape: ${hyperparameters.latent_shape}
      output_shape: ${dataset.params.observation_shape}
      save_activations: ${hyperparameters.save_activations}
