defaults:
  - encoder: convolutional
  - decoder: convolutional
  - reconstruction_loss_fn: bernoulli

name: dip_vae_i
_target_: vae_ld.models.vaes.DIPVAE
# lambda_off_diag tested by locatello et al.: [1, 2, 5, 10, 20, 50]
lambda_off_diag: 1
# lambda_diag tested by locatello et al.: [10, 20, 50, 100, 200, 500]
lambda_diag: 10
dip_type: i
input_shape: ${dataset.observation_shape}
latent_shape: ${latent_shape}