defaults:
  - encoder: convolutional
  - decoder: convolutional
  - reconstruction_loss_fn: bernoulli

name: factor_vae
_target_: vae_ld.models.vaes.FactorVAE
 # Gamma tested by Locatello et al.: [10, 20, 30, 40, 50, 100]
gamma: 10
input_shape: ${dataset.observation_shape}
latent_shape: ${latent_shape}
discriminator:
  _target_: vae_ld.models.discriminators.FullyConnectedDiscriminator
  input_shape: ${latent_shape}
  optimizer:
    _target_: tensorflow.keras.optimizers.Adam
    learning_rate: 0.0001
    beta_1: 0.5
    beta_2: 0.9
    epsilon: 1e-8
    amsgrad: false