model:
  class: src.models.vaes.VAE
  params:
    save_activations: ${hyperparameters.save_activations}
  encoder:
    class: src.models.encoders.MnistEncoder
    params:
      input_shape: ${dataset.params.observation_shape}
      output_shape: ${hyperparameters.latent_shape}
      save_activations: ${hyperparameters.save_activations}
  decoder:
    class: src.models.decoders.MnistDecoder
    params:
      input_shape: ${hyperparameters.latent_shape}
      output_shape: ${dataset.params.observation_shape}
      save_activations: ${hyperparameters.save_activations}