models_path: ???
n_samples: 10000
seed: 0
model_names:
  - beta_vae
param_values:
  - 1

defaults:
  - _self_
  - dataset: cars

cka:
  _target_: vae_ld.learning_dynamics.cka.CKA
  debiased: false

hydra:
  run:
    dir: ${oc.env:XP_PATH}/VAE_ld/${hydra.job.name}/${model_names}/${dataset.name}/${param_values}/${n_samples}
  sweep:
    dir: ${oc.env:XP_PATH}/VAE_ld/${hydra.job.name}/${model_names}/${dataset.name}/${param_values}
    subdir: ${n_samples}
  job:
    config:
      override_dirname:
        kv_sep: _
        item_sep: /
