m1_path: ???
m2_path: ???
n_samples: 10000
seed: 0
m1_name: beta_vae
m2_name: beta_vae
p1_value: 1
p2_value: 1

defaults:
  - _self_
  - dataset: cars

cka:
  _target_: vae_ld.learning_dynamics.cka.CKA
  debiased: false

hydra:
  run:
    dir: ${oc.env:XP_PATH}/VAE_ld/${hydra.job.name}/${dataset.name}/${m1_name}_${p1_value}/${m2_name}_${p2_value}
  sweep:
    dir: ${oc.env:XP_PATH}/VAE_ld/${hydra.job.name}/${dataset.name}/${m1_name}_${p1_value}
    subdir: ${m2_name}_${p2_value}
  job:
    config:
      override_dirname:
        kv_sep: _
        item_sep: /
