n_samples: 10000
seed: 0
m1_name: beta_vae
m2_name: beta_vae
p1_value: 1
p2_value: 1
m1_path: ${oc.env:XP_PATH}/VAE_ld/train/${m1_name}/${dataset.name}/${p1_name}/*/checkpoint/*
m2_path: ${oc.env:XP_PATH}/VAE_ld/train/${m2_name}/${dataset.name}/${p2_name}/*/checkpoint/*

defaults:
  - _self_
  - dataset: cars

cka:
  _target_: vae_ld.learning_dynamics.cka.CKA
  debiased: false

hydra:
  run:
    dir: ${oc.env:XP_PATH}/VAE_ld/${hydra.job.name}/${dataset.name}/${m1_name}_${p1_value}/${m2_name}_${p2_value}
  sweep:
    dir: ${oc.env:XP_PATH}/VAE_ld/${hydra.job.name}/${dataset.name}/${m1_name}_${p1_value}
    subdir: ${m2_name}_${p2_value}
  job:
    config:
      override_dirname:
        kv_sep: _
        item_sep: /
