models_path: ???
n_samples: 10000
seed: 0
defaults:
  - _self_
  - dataset: cars

cka:
  _target_: vae_ld.learning_dynamics.cka.CKA
  kernel: vae_ld.learning_dynamics.cka.linear_kernel
  debiased: false
