_target_: vae_ld.data.cars3d.Cars3D
path: /media/bonheml/phd_data/Datasets/cars
observation_shape: [32,32,3]
url: http://www.scottreed.info/files/nips2015-analogy-data.tar.gz
data_size: 17600
name: cars3d
