name: aggregate

fn:
  _target_: vae_ld.visualisation.ides.aggregate_ides
  input_dir: ${oc.env:XP_PATH}/get_layers_estimate/${estimator}/*/${dataset_name}/${estimator}_${dataset_name}_${model_name}_${param_name}_${param_value}_seed*.tsv
  save_file: ${estimator}_${dataset_name}_${model_name}_${param_name}_${param_value}_${batch_size}_samples_agg.tsv
  overwrite: ${overwrite}