name: aggregate

fn:
  _target_: vae_ld.visualisation.ides.aggregate_ides
  input_dir: ${oc.env:XP_PATH}/get_data_ide/*/${dataset_name}/IDE_${dataset_name}_${model_name}_${param_name}_${param_value}_seed*.tsv
  save_file: IDE_${dataset_name}_${model_name}_${param_name}_${param_value}_${batch_size}_samples_agg.tsv
  overwrite: ${overwrite}