name: data_ides

fn:
  _target_: vae_ld.visualisation.ides.plot_data_ides
  input_dir: ${oc.env:XP_PATH}/visualise_ides/${estimator}/aggregate/*/${model_name}
  save_file: ${model_name}_${param_name}_${param_value}_${batch_size}_samples_${estimator}_data.pdf
  overwrite: ${overwrite}
