name: layers_ides

fn:
  _target_: vae_ld.visualisation.ides.plot_layers_ides
  input_file: ${oc.env:XP_PATH}/visualise_ides/aggregate/${dataset_name}/${model_name}/IDE_${dataset_name}_${model_name}_${param_name}_${param_value}_${batch_size}_samples_agg.tsv
  save_file: ${dataset_name}_${model_name}_${param_name}_${param_value}_${batch_size}_samples_IDE_layers.pdf
  overwrite: ${overwrite}
  hue: Number of latent dimensions