defaults:
  - _self_
  - encoder: convolutional
  - decoder: convolutional
  - reconstruction_loss_fn: bernoulli
  - regularisation_loss_fn: kld

name: annealed_vae

_target_: vae_ld.models.vaes.AnnealedVAE
gamma: 1000
# Max capacity tested by Locatello et al. : [5, 10, 25, 50, 75, 100]
max_capacity: ${param_value}
iteration_threshold: 100000
input_shape: ${dataset.observation_shape}
latent_shape: ${latent_shape}
n_samples: ${n_samples}

