defaults:
  - _self_
  - encoder: convolutional
  - decoder: convolutional
  - reconstruction_loss_fn: bernoulli

name: annealed_vae_b

_target_: vae_ld.models.vaes.AnnealedVAEB
iteration_threshold: ${param_value}
input_shape: ${dataset.observation_shape}
latent_shape: ${latent_shape}