name: beta_vae

defaults:
  - _self_
  - encoder: convolutional
  - decoder: convolutional
  - reconstruction_loss_fn: bernoulli

_target_: vae_ld.models.vaes.BetaVAE
# Beta tested by Locatello et al.: [1, 2, 4, 6, 8, 16]
beta: ${param_value}
input_shape: ${dataset.observation_shape}
latent_shape: ${latent_shape}