defaults:
  - _self_
  - encoder: convolutional
  - decoder: convolutional
  - reconstruction_loss_fn: bernoulli
  - regularisation_loss_fn: kld

name: dip_vae_i

_target_: vae_ld.models.vaes.DIPVAE
# lambda_off_diag tested by locatello et al.: [1, 2, 5, 10, 20, 50]
lambda_off_diag: ${param_name}
lambda_factor: 10
dip_type: i
input_shape: ${dataset.observation_shape}
latent_shape: ${latent_shape}
n_samples: ${n_samples}
