defaults:
  - _self_
  - encoder: convolutional
  - decoder: convolutional
  - reconstruction_loss_fn: bernoulli

name: dip_vae_ii

_target_: vae_ld.models.vaes.DIPVAE
# lambda_off_diag tested by locatello et al.: [1, 2, 5, 10, 20, 50]
lambda_off_diag: ${param_value}
lambda_factor: 1
dip_type: ii
input_shape: ${dataset.observation_shape}
latent_shape: ${latent_shape}
