name: gon

defaults:
  - _self_
  - encoder: gon
  - decoder: convolutional
  - reconstruction_loss_fn: bernoulli

_target_: vae_ld.models.gons.VGON
input_shape: ${latent_shape}
latent_shape: ${latent_shape}
