name: ivae

defaults:
  - _self_
  - encoder: iconvolutional
  - decoder: convolutional
  - prior_model: prior
  - reconstruction_loss_fn: bernoulli
  - regularisation_loss_fn: kld

_target_: vae_ld.models.vaes.IVAE
in_shape: ${dataset.observation_shape}
latent_shape: ${latent_shape}
prior_shape: ${dataset.n_factors}