batch_size: 64
training_steps: 300000
latent_shape: 10
seed: 0
param_value: 1
restart_from_last_checkpoint: true


defaults:
  - _self_
  - dataset: cars
  - sampling: sampler
  - optimizer: adam
  - model: beta_vae
  - callbacks:
      - model_checkpoint
      - tensorboard
      - image_generator

hydra:
  run:
    dir: ${oc.env:XP_PATH}/VAE_ld/${hydra.job.name}/${model.name}/${dataset.name}/${param_value}/${seed}
  sweep:
    dir: ${oc.env:XP_PATH}/VAE_ld/${hydra.job.name}/${model.name}/${dataset.name}/${param_value}
    subdir: ${seed}
  job:
    config:
      override_dirname:
        kv_sep: _
        item_sep: /