batch_size: 64
training_steps: 300000
latent_shape: 10
seed: 1


defaults:
  - _self_
  - dataset: cars
  - sampling: sampler
  - optimizer: adam
  - model: beta_vae
  - callbacks:
      - model_checkpoint
      - tensorboard
      - image_generator

hydra:
  run:
    dir: ${oc.env:XP_PATH}/VAE_ld/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}/${model.name}/${dataset.name}/${hydra.job.override_dirname}
  sweep:
    dir: ${oc.env:XP_PATH}/VAE_ld/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}/${model.name}/${dataset.name}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        kv_sep: _
        item_sep: /