name: aggregate

fn:
  _target_: vae_ld.learning_dynamics.visualisation.aggregate_cka
  input_dir: ${oc.env:XP_PATH}/VAE_ld/compute_cka/${dataset_name}/${m1_name}/*/*/*/*/*
  save_file: ${dataset_name}_${m1_name}_agg.tsv