name: cka_layer_list

fn:
  _target_: vae_ld.visualisation.cka.avg_cka_layer_list
  regularisation: 1
  layer: "encoder/z_mean"
  target: decoder
  save_file: cka_${dataset_name}_${m1_name}_${visualisation_tool.fn.regularisation}_encoder_${visualisation_tool.fn.layer}_${visualisation_tool.fn.target}.pdf
  input_file: ${oc.env:XP_PATH}/VAE_ld/visualise_cka/aggregate/${dataset_name}/${m1_name}/${dataset_name}_${m1_name}_agg.tsv