name: heatmap

fn:
  _target_: vae_ld.visualisation.similarity.similarity_heatmap
  metric_name: ${metric_name}
  input_file: ${oc.env:XP_PATH}/VAE_ld/visualise_similarity/latent_${latent_dim}/aggregate/${dataset_name}/${metric_name}/${m1_name}/${metric_name}_${dataset_name}_${m1_name}_agg.tsv
  overwrite: ${overwrite}
