name: heatmap

fn:
  _target_: vae_ld.visualisation.similarity.similarity_heatmap
  input_dir: ${oc.env:XP_PATH}/compute_similarity/latent_${latent_dim}/${dataset_name}/${metric_name}/${m1_name}/*/*/*/*/*
  overwrite: ${overwrite}
