name: heatmap

fn:
  _target_: vae_ld.visualisation.similarity.similarity_heatmap
  input_file: ${oc.env:XP_PATH}/visualise_similarity/latent_${latent_dim}/aggregate/${dataset_name}/${metric_name}/${m1_name}/${metric_name}_${dataset_name}_${m1_name}_agg.tsv
  m1_name: ${m1_name}
  m1_epoch: 1
  p1_name: beta
  p1_value: 1
  m2_name: beta_vae
  m2_epoch: 1
  p2_name: beta
  p2_value: 1
  metric: ${metric_name}
  save_file: ${m1_name}_${visualisation_tool.fn.p1_value}_epoch_${visualisation_tool.fn.m1_epoch}_${visualisation_tool.fn.m2_name}_${visualisation_tool.fn.p2_value}_epoch_${visualisation_tool.fn.m2_epoch}.pdf
  overwrite: ${overwrite}
