name: layer_list

fn:
  _target_: vae_ld.visualisation.similarity.avg_similarity_layer_list
  metric_name: ${metric_name}
  regularisation: 1
  layer: "input"
  target: encoder
  save_file: ${metric_name}_${dataset_name}_${m1_name}_${visualisation_tool.fn.regularisation}_${visualisation_tool.fn.layer}_${visualisation_tool.fn.target}.pdf
  input_file: ${oc.env:XP_PATH}/visualise_similarity/latent_${latent_dim}/aggregate/${dataset_name}/${metric_name}/${m1_name}/${metric_name}_${dataset_name}_${m1_name}_agg.tsv
  overwrite: ${overwrite}
