name: tsne

fn:
  _target_: vae_ld.visualisation.similarity.plot_tsne
  input_dir: ${oc.env:XP_PATH}/compute_similarity/latent_${latent_dim}/${dataset_name}/${metric_name}/${m1_name}/*/*/*/*/*
  save_file: ${metric_name}_${dataset_name}_${m1_name}_tsne_${visualisation_tool.fn.target}.pdf
  target: "seed"
  overwrite: ${overwrite}
